"use client"

import { useRef } from "react"
import html2canvas from "html2canvas"

interface ShareableGraphicProps {
  beforeSrc: string
  afterSrc: string
  clinicName: string
  clinicLogo?: string | null
}

export function ShareableGraphic({ beforeSrc, afterSrc, clinicName, clinicLogo }: ShareableGraphicProps) {
  const graphicRef = useRef<HTMLDivElement>(null)

  const handleDownload = async () => {
    if (!graphicRef.current) return

    const canvas = await html2canvas(graphicRef.current, {
      scale: 2, // جودة عالية
      useCORS: true, // عشان يقدر يقرأ صور الـ Cloudinary
      backgroundColor: "#ffffff",
    })
    const link = document.createElement("a")
    link.download = `before-after-${clinicName.replace(/\s+/g, '-')}.png`
    link.href = canvas.toDataURL("image/png")
    link.click()
  }

  return (
    <div className="space-y-4">
      {/* زرار التحميل */}
      <button
        onClick={handleDownload}
        className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-[#5BC0BE] to-[#6B9CFF] px-5 py-2.5 text-sm font-semibold text-white shadow-lg hover:-translate-y-0.5 transition-all"
      >
        📥 Download for Social Media
      </button>

      {/* ✅ التصميم اللي هيترسم كصورة (Hidden Layout عشان ميبانش في الصفحة مدمار) */}
      <div className="absolute left-[-9999px] top-[-9999px]">
        <div 
          ref={graphicRef} 
          style={{ 
            width: "1080px", 
            height: "1080px", 
            padding: "40px", 
            backgroundColor: "#ffffff", 
            fontFamily: "'Cairo', sans-serif",
            display: "flex",
            flexDirection: "column",
            gap: "20px"
          }}
        >
          {/* Header with Logo & Clinic Name */}
          <div style={{ display: "flex", alignItems: "center", gap: "20px", marginBottom: "10px" }}>
            {clinicLogo && <img src={clinicLogo} style={{ width: "80px", height: "80px", borderRadius: "50%", objectFit: "cover" }} />}
            <h1 style={{ fontSize: "48px", fontWeight: "bold", color: "#0f766e", margin: 0 }}>{clinicName}</h1>
          </div>

          {/* Before & After Title */}
          <div style={{ textAlign: "center", backgroundColor: "#0f766e", color: "white", padding: "15px", borderRadius: "12px" }}>
            <h2 style={{ fontSize: "40px", margin: 0 }}>✨ Before & After ✨</h2>
          </div>

          {/* Images Side by Side */}
          <div style={{ display: "flex", gap: "20px", flex: 1 }}>
            <div style={{ flex: 1, position: "relative" }}>
              <img src={beforeSrc} style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: "16px" }} />
              <div style={{ position: "absolute", bottom: "20px", left: "20px", backgroundColor: "rgba(0,0,0,0.6)", color: "white", padding: "8px 20px", borderRadius: "20px", fontSize: "24px" }}>Before</div>
            </div>
            <div style={{ flex: 1, position: "relative" }}>
              <img src={afterSrc} style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: "16px" }} />
              <div style={{ position: "absolute", bottom: "20px", right: "20px", backgroundColor: "#0f766e", color: "white", padding: "8px 20px", borderRadius: "20px", fontSize: "24px" }}>After</div>
            </div>
          </div>

          {/* Footer */}
          <div style={{ textAlign: "center", color: "#94a3b8", fontSize: "20px", marginTop: "10px" }}>
            Generated by Eyadti System
          </div>
        </div>
      </div>
    </div>
  )
}